In [256]:
import pandas as pd
import numpy as np
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')

In [257]:
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [258]:
unaccompanied_minor = pd.read_csv('Unaccompanied Minor.csv')
checkout = pd.read_csv('checkout.csv')
products_and_services = pd.read_csv('Products and Services.csv')
schedule_change = pd.read_csv('Schedule Change.csv')
checkin = pd.read_csv('Check In.csv')
other_topics =pd.read_csv('Other Topics.csv')
etc = pd.read_csv('ETC.csv')
baggage = pd.read_csv('Baggage.csv')
voluntary_change = pd.read_csv('Voluntary Change.csv')
nan = pd.read_csv('nan.csv')

In [259]:
mileage_plus = pd.read_csv('Mileage Plus.csv')
irrops = pd.read_csv('IRROPS.csv')
upgrade = pd.read_csv('Upgrade.csv')
traveler_updates = pd.read_csv('Traveler Updates.csv')
communications = pd.read_csv('Communications.csv')
seating = pd.read_csv('Seating.csv')
postflight = pd.read_csv('Post Flight.csv')
voluntary_cancel = pd.read_csv('Voluntary Cancel.csv')
disability = pd.read_csv('Disability.csv')
digital_support = pd.read_csv('Digital Support.csv')
booking = pd.read_csv('Booking.csv')

In [260]:
unaccompanied_minor.head()

,Unnamed: 0,Unnamed: 0.1,call_id,customer_id,agent_id,call_transcript,call_start_datetime,agent_assigned_datetime,call_end_datetime,primary_call_reason,topic_distribution,dominant_topic,topic_keywords
0,409,409,4837646327,6025575913,390819,daniel assist daniel mad suppos york san franc...,2024-08-02 10:51:00,2024-08-02 11:03:00,2024-08-02 11:34:00,Unaccompanied Minor,[0.00264936 0.00262036 0.66235851 0.33237177],2,"Topic 1: return, monday, saturday, email, john..."
1,837,837,9775075849,6835065735,436160,john york tri uhh bq348921 background sorri ki...,2024-08-03 08:07:00,2024-08-03 08:19:00,2024-08-03 08:25:00,Unaccompanied Minor,[0.99241378 0.00249397 0.00260048 0.00249177],0,"Topic 1: return, monday, saturday, email, john..."
2,2035,2035,4762278577,260825358,852493,adam adam come 1234 question statu upgrad requ...,2024-08-04 08:04:00,2024-08-04 08:16:00,2024-08-04 08:19:00,Unaccompanied Minor,[0.99364683 0.00214004 0.00210364 0.00210949],0,"Topic 1: return, monday, saturday, email, john..."
3,3140,3140,1208112463,1785267688,825827,london worri busi concern statu keyboard ua908...,2024-08-05 08:29:00,2024-08-05 08:41:00,2024-08-05 08:44:00,Unaccompanied Minor,[0.58591008 0.0025535 0.40898485 0.00255157],0,"Topic 1: return, monday, saturday, email, john..."
4,3680,3680,3604539305,6338257519,619806,susan complain took denver three explan miss i...,2024-08-01 10:05:00,2024-08-01 10:16:00,2024-08-01 10:19:00,Unaccompanied Minor,[0.0026147 0.00262246 0.99215402 0.00260882],2,"Topic 1: return, monday, saturday, email, john..."

In [262]:
dataframes = [
    unaccompanied_minor, checkout, products_and_services, 
    schedule_change, checkin, other_topics, etc, baggage, voluntary_change,nan, 
     mileage_plus, irrops, upgrade, traveler_updates, 
    communications, seating, postflight, voluntary_cancel, disability, 
    digital_support, booking
]
reason_dict = {}

for i, df in enumerate(dataframes, 1):
    key_name = f'reason_{i}'  # Create keys like reason_1, reason_2, etc.
    reason_dict[key_name] = df  # Assign the DataFrame to the key

# Optional: Print the dictionary keys to confirm
print(reason_dict.keys())

dict_keys(['reason_1', 'reason_2', 'reason_3', 'reason_4', 'reason_5', 'reason_6', 'reason_7', 'reason_8', 'reason_9', 'reason_10', 'reason_11', 'reason_12', 'reason_13', 'reason_14', 'reason_15', 'reason_16', 'reason_17', 'reason_18', 'reason_19', 'reason_20', 'reason_21'])

In [269]:
reason_dict['reason_14']['dominant_topic'].value_counts()

2    342
1    222
3    207
0    166
Name: dominant_topic, dtype: int64

In [270]:
for reason,df in reason_dict.items():
    if 'call_start_datetime' in df.columns:
        df['hour'] = pd.to_datetime(df['call_start_datetime']).dt.hour

In [271]:

selected_columns = ['call_id','call_start_datetime','agent_assigned_datetime','call_end_datetime','primary_call_reason','dominant_topic','topic_keywords','hour']  # Replace with actual column names

filtered_reason_dict = {}

for key, df in reason_dict.items():
    available_columns = [col for col in selected_columns if col in df.columns]
    
    filtered_reason_dict[key] = df[available_columns]
    
    print(f"Filtered DataFrame for {key}:")
    print(filtered_reason_dict[key].head())

Filtered DataFrame for reason_1:
      call_id  call_start_datetime agent_assigned_datetime  \
0  4837646327  2024-08-02 10:51:00     2024-08-02 11:03:00
1  9775075849  2024-08-03 08:07:00     2024-08-03 08:19:00
2  4762278577  2024-08-04 08:04:00     2024-08-04 08:16:00
3  1208112463  2024-08-05 08:29:00     2024-08-05 08:41:00
4  3604539305  2024-08-01 10:05:00     2024-08-01 10:16:00

     call_end_datetime  primary_call_reason  dominant_topic  \
0  2024-08-02 11:34:00  Unaccompanied Minor               2
1  2024-08-03 08:25:00  Unaccompanied Minor               0
2  2024-08-04 08:19:00  Unaccompanied Minor               0
3  2024-08-05 08:44:00  Unaccompanied Minor               0
4  2024-08-01 10:19:00  Unaccompanied Minor               2

                                      topic_keywords  hour
0  Topic 1: return, monday, saturday, email, john...    10
1  Topic 1: return, monday, saturday, email, john...     8
2  Topic 1: return, monday, saturday, email, john...     8
3  Topic 1: return, monday, saturday, email, john...     8
4  Topic 1: return, monday, saturday, email, john...    10
Filtered DataFrame for reason_2:
      call_id  call_start_datetime agent_assigned_datetime  \
0  3297807483  2024-08-01 13:28:00     2024-08-01 13:38:00
1  8971220589  2024-08-01 14:02:00     2024-08-01 14:17:00
2    44201418  2024-08-01 16:21:00     2024-08-01 16:30:00
3  5715352709  2024-08-18 18:03:00     2024-08-18 18:18:00
4  8960689724  2024-08-01 17:51:00     2024-08-01 18:01:00

     call_end_datetime primary_call_reason  dominant_topic  \
0  2024-08-01 13:46:00            Checkout               2
1  2024-08-01 14:21:00            Checkout               1
2  2024-08-01 16:41:00            Checkout               2
3  2024-08-18 18:27:00            Checkout               3
4  2024-08-01 18:17:00            Checkout               1

                                      topic_keywords  hour
0  Topic 1: credit, refund, offer, ticket, futur,...    13
1  Topic 1: credit, refund, offer, ticket, futur,...    14
2  Topic 1: credit, refund, offer, ticket, futur,...    16
3  Topic 1: credit, refund, offer, ticket, futur,...    18
4  Topic 1: credit, refund, offer, ticket, futur,...    17
Filtered DataFrame for reason_3:
      call_id  call_start_datetime agent_assigned_datetime  \
0  6186829781  2024-08-01 08:10:00     2024-08-01 08:15:00
1   438834035  2024-08-01 09:22:00     2024-08-01 09:27:00
2  4573865210  2024-08-01 09:29:00     2024-08-01 09:35:00
3  2504838636  2024-08-01 11:05:00     2024-08-01 11:12:00
4  9656410826  2024-08-01 11:30:00     2024-08-01 11:34:00

     call_end_datetime    primary_call_reason  dominant_topic  \
0  2024-08-01 08:22:00  Products and Services               0
1  2024-08-01 09:37:00  Products and Services               1
2  2024-08-01 09:39:00  Products and Services               1
3  2024-08-01 11:21:00  Products and Services               0
4  2024-08-01 11:36:00  Products and Services               0

                                      topic_keywords  hour
0  Topic 1: sir, voucher, refund, apolog, guess, ...     8
1  Topic 1: sir, voucher, refund, apolog, guess, ...     9
2  Topic 1: sir, voucher, refund, apolog, guess, ...     9
3  Topic 1: sir, voucher, refund, apolog, guess, ...    11
4  Topic 1: sir, voucher, refund, apolog, guess, ...    11
Filtered DataFrame for reason_4:
      call_id  call_start_datetime agent_assigned_datetime  \
0  5447500829  2024-08-01 11:11:00     2024-08-01 11:14:00
1  2878255662  2024-08-01 16:49:00     2024-08-01 16:53:00
2  2261446423  2024-08-02 13:22:00     2024-08-02 13:27:00
3  8302569878  2024-08-02 14:13:00     2024-08-02 14:18:00
4  4995330155  2024-08-07 17:59:00     2024-08-07 18:03:00

     call_end_datetime primary_call_reason  dominant_topic  \
0  2024-08-01 11:32:00     Schedule Change               0
1  2024-08-01 16:56:00     Schedule Change               0
2  2024-08-02 13:51:00     Schedule Change               3
3  2024-08-02 14:23:00     Schedule Change               1
4  2024-08-07 18:03:00     Schedule Change               2

                                      topic_keywords  hour
0  Topic 1: tomorrow, connect, sir, ugh, guess, y...    11
1  Topic 1: tomorrow, connect, sir, ugh, guess, y...    16
2  Topic 1: tomorrow, connect, sir, ugh, guess, y...    13
3  Topic 1: tomorrow, connect, sir, ugh, guess, y...    14
4  Topic 1: tomorrow, connect, sir, ugh, guess, y...    17
Filtered DataFrame for reason_5:
      call_id  call_start_datetime agent_assigned_datetime  \
0  4887800277  2024-08-01 10:44:00     2024-08-01 10:52:00
1  4925500008  2024-08-01 12:01:00     2024-08-01 12:09:00
2  2025546675  2024-08-01 12:25:00     2024-08-01 12:32:00
3  7209830654  2024-08-23 09:04:00     2024-08-23 09:12:00
4  6402940410  2024-08-01 23:30:00     2024-08-01 23:34:00

     call_end_datetime primary_call_reason  dominant_topic  \
0  2024-08-01 10:54:00            Check In               1
1  2024-08-01 12:12:00            Check In               3
2  2024-08-01 12:36:00            Check In               2
3  2024-08-23 09:20:00            Check In               2
4  2024-08-01 23:43:00            Check In               3

                                      topic_keywords  hour
0  Topic 1: san, francisco, safe, question, feel,...    10
1  Topic 1: san, francisco, safe, question, feel,...    12
2  Topic 1: san, francisco, safe, question, feel,...    12
3  Topic 1: san, francisco, safe, question, feel,...     9
4  Topic 1: san, francisco, safe, question, feel,...    23
Filtered DataFrame for reason_6:
      call_id  call_start_datetime agent_assigned_datetime  \
0  8753344381  2024-08-01 10:44:00     2024-08-01 10:47:00
1  6363170199  2024-08-01 16:27:00     2024-08-01 16:32:00
2  1369269893  2024-08-01 16:36:00     2024-08-01 16:41:00
3  6121033173  2024-08-01 16:42:00     2024-08-01 16:46:00
4  6073323445  2024-08-02 05:04:00     2024-08-02 05:08:00

     call_end_datetime primary_call_reason  dominant_topic  \
0  2024-08-01 10:53:00        Other Topics               1
1  2024-08-01 16:40:00        Other Topics               1
2  2024-08-01 16:44:00        Other Topics               0
3  2024-08-01 16:48:00        Other Topics               1
4  2024-08-02 05:21:00        Other Topics               2

                                      topic_keywords  hour
0  Topic 1: weather, question, departur, safe, ba...    10
1  Topic 1: weather, question, departur, safe, ba...    16
2  Topic 1: weather, question, departur, safe, ba...    16
3  Topic 1: weather, question, departur, safe, ba...    16
4  Topic 1: weather, question, departur, safe, ba...     5
Filtered DataFrame for reason_7:
      call_id  call_start_datetime agent_assigned_datetime  \
0  4970876319  2024-08-01 10:13:00     2024-08-01 10:20:00
1  2906538157  2024-08-01 11:05:00     2024-08-01 11:15:00
2  8104918573  2024-08-01 11:26:00     2024-08-01 11:33:00
3  2987351970  2024-08-01 13:04:00     2024-08-01 13:11:00
4  1574660319  2024-08-01 13:37:00     2024-08-01 13:48:00

     call_end_datetime primary_call_reason  dominant_topic  \
0  2024-08-01 10:24:00                 ETC               0
1  2024-08-01 11:35:00                 ETC               0
2  2024-08-01 12:05:00                 ETC               3
3  2024-08-01 13:21:00                 ETC               0
4  2024-08-01 14:11:00                 ETC               1

                                      topic_keywords  hour
0  Topic 1: tomorrow, connect, denver, miss, apol...    10
1  Topic 1: tomorrow, connect, denver, miss, apol...    11
2  Topic 1: tomorrow, connect, denver, miss, apol...    11
3  Topic 1: tomorrow, connect, denver, miss, apol...    13
4  Topic 1: tomorrow, connect, denver, miss, apol...    13
Filtered DataFrame for reason_8:
      call_id  call_start_datetime agent_assigned_datetime  \
0   687556900  2024-08-01 10:07:00     2024-08-01 10:16:00
1  2835524012  2024-08-01 10:55:00     2024-08-01 11:04:00
2  4350015240  2024-08-01 10:52:00     2024-08-01 11:03:00
3  4075573598  2024-08-01 12:32:00     2024-08-01 12:43:00
4  1589048482  2024-08-01 14:08:00     2024-08-01 14:16:00

     call_end_datetime primary_call_reason  dominant_topic  \
0  2024-08-01 10:19:00             Baggage               2
1  2024-08-01 11:07:00             Baggage               1
2  2024-08-01 11:08:00             Baggage               0
3  2024-08-01 12:58:00             Baggage               3
4  2024-08-01 14:22:00             Baggage               1

                                      topic_keywords  hour
0  Topic 1: 150, friday, return, great, monday, t...    10
1  Topic 1: 150, friday, return, great, monday, t...    10
2  Topic 1: 150, friday, return, great, monday, t...    10
3  Topic 1: 150, friday, return, great, monday, t...    12
4  Topic 1: 150, friday, return, great, monday, t...    14
Filtered DataFrame for reason_9:
      call_id  call_start_datetime agent_assigned_datetime  \
0  3326242904  2024-08-01 08:24:00     2024-08-01 08:33:00
1  9605740557  2024-08-01 08:47:00     2024-08-01 08:55:00
2   750943900  2024-08-01 09:11:00     2024-08-01 09:18:00
3  3105257948  2024-08-01 09:45:00     2024-08-01 09:53:00
4  8485536310  2024-08-01 10:03:00     2024-08-01 10:13:00

     call_end_datetime primary_call_reason  dominant_topic  \
0  2024-08-01 08:36:00    Voluntary Change               0
1  2024-08-01 09:00:00    Voluntary Change               2
2  2024-08-01 09:24:00    Voluntary Change               2
3  2024-08-01 10:02:00    Voluntary Change               2
4  2024-08-01 10:27:00    Voluntary Change               0

                                      topic_keywords  hour
0  Topic 1: 150, waiv, monday, differ, pay, credi...     8
1  Topic 1: 150, waiv, monday, differ, pay, credi...     8
2  Topic 1: 150, waiv, monday, differ, pay, credi...     9
3  Topic 1: 150, waiv, monday, differ, pay, credi...     9
4  Topic 1: 150, waiv, monday, differ, pay, credi...    10
Filtered DataFrame for reason_10:
Empty DataFrame
Columns: [call_id, call_start_datetime, agent_assigned_datetime, call_end_datetime, primary_call_reason, hour]
Index: []
Filtered DataFrame for reason_11:
      call_id  call_start_datetime agent_assigned_datetime  \
0  3766236397  2024-08-01 08:10:00     2024-08-01 08:16:00
1  8350670977  2024-08-01 08:20:00     2024-08-01 08:28:00
2  1950793040  2024-08-01 09:49:00     2024-08-01 09:54:00
3    14764275  2024-08-01 10:23:00     2024-08-01 10:28:00
4  7692676121  2024-08-01 11:39:00     2024-08-01 11:46:00

     call_end_datetime primary_call_reason  dominant_topic  \
0  2024-08-01 08:18:00        Mileage Plus               0
1  2024-08-01 08:59:00        Mileage Plus               2
2  2024-08-01 09:55:00        Mileage Plus               3
3  2024-08-01 10:40:00        Mileage Plus               1
4  2024-08-01 11:58:00        Mileage Plus               3

                                      topic_keywords  hour
0  Topic 1: refund, voucher, experi, miss, provid...     8
1  Topic 1: refund, voucher, experi, miss, provid...     8
2  Topic 1: refund, voucher, experi, miss, provid...     9
3  Topic 1: refund, voucher, experi, miss, provid...    10
4  Topic 1: refund, voucher, experi, miss, provid...    11
Filtered DataFrame for reason_12:
      call_id  call_start_datetime agent_assigned_datetime  \
0  9426822806  2024-08-01 07:28:00     2024-08-01 07:34:00
1  9993775527  2024-08-01 07:54:00     2024-08-01 08:02:00
2  5450426391  2024-08-01 07:55:00     2024-08-01 08:03:00
3  8245792247  2024-08-01 08:26:00     2024-08-01 08:33:00
4  9795806060  2024-08-01 08:38:00     2024-08-01 08:44:00

     call_end_datetime primary_call_reason  dominant_topic  \
0  2024-08-01 07:35:00              IRROPS               2
1  2024-08-01 08:05:00              IRROPS               3
2  2024-08-01 08:29:00              IRROPS               1
3  2024-08-01 08:55:00              IRROPS               1
4  2024-08-01 08:47:00              IRROPS               2

                                      topic_keywords  hour
0  Topic 1: weather, london, feel, question, safe...     7
1  Topic 1: weather, london, feel, question, safe...     7
2  Topic 1: weather, london, feel, question, safe...     7
3  Topic 1: weather, london, feel, question, safe...     8
4  Topic 1: weather, london, feel, question, safe...     8
Filtered DataFrame for reason_13:
      call_id  call_start_datetime agent_assigned_datetime  \
0  3266080628  2024-08-01 07:17:00     2024-08-01 07:22:00
1   952819626  2024-08-01 09:44:00     2024-08-01 09:48:00
2  6218069933  2024-08-01 10:01:00     2024-08-01 10:05:00
3  1478363853  2024-08-01 11:10:00     2024-08-01 11:16:00
4  8986373828  2024-08-01 11:55:00     2024-08-01 12:02:00

     call_end_datetime primary_call_reason  dominant_topic  \
0  2024-08-01 07:27:00             Upgrade               3
1  2024-08-01 09:53:00             Upgrade               1
2  2024-08-01 10:10:00             Upgrade               2
3  2024-08-01 11:21:00             Upgrade               0
4  2024-08-01 12:15:00             Upgrade               1

                                      topic_keywords  hour
0  Topic 1: 150, monday, return, waiv, differ, tu...     7
1  Topic 1: 150, monday, return, waiv, differ, tu...     9
2  Topic 1: 150, monday, return, waiv, differ, tu...    10
3  Topic 1: 150, monday, return, waiv, differ, tu...    11
4  Topic 1: 150, monday, return, waiv, differ, tu...    11
Filtered DataFrame for reason_14:
      call_id  call_start_datetime agent_assigned_datetime  \
0  5555212163  2024-08-01 06:22:00     2024-08-01 06:34:00
1  6803900104  2024-08-01 09:08:00     2024-08-01 09:19:00
2  9354619428  2024-08-01 09:33:00     2024-08-01 09:44:00
3  4222807940  2024-08-01 12:04:00     2024-08-01 12:16:00
4  1765808092  2024-08-01 13:52:00     2024-08-01 14:03:00

     call_end_datetime primary_call_reason  dominant_topic  \
0  2024-08-01 06:39:00    Traveler Updates               2
1  2024-08-01 09:23:00    Traveler Updates               2
2  2024-08-01 09:46:00    Traveler Updates               3
3  2024-08-01 12:30:00    Traveler Updates               1
4  2024-08-01 14:08:00    Traveler Updates               2

                                      topic_keywords  hour
0  Topic 1: monday, tuesday, 150, waiv, sam, pay,...     6
1  Topic 1: monday, tuesday, 150, waiv, sam, pay,...     9
2  Topic 1: monday, tuesday, 150, waiv, sam, pay,...     9
3  Topic 1: monday, tuesday, 150, waiv, sam, pay,...    12
4  Topic 1: monday, tuesday, 150, waiv, sam, pay,...    13
Filtered DataFrame for reason_15:
      call_id  call_start_datetime agent_assigned_datetime  \
0  4963458977  2024-08-01 06:04:00     2024-08-01 06:08:00
1  2457729996  2024-08-01 06:50:00     2024-08-01 06:54:00
2   236200708  2024-08-01 09:42:00     2024-08-01 09:46:00
3  8646387952  2024-08-01 11:19:00     2024-08-01 11:24:00
4  6803937559  2024-08-01 11:42:00     2024-08-01 11:46:00

     call_end_datetime primary_call_reason  dominant_topic  \
0  2024-08-01 06:11:00      Communications               0
1  2024-08-01 06:58:00      Communications               0
2  2024-08-01 10:55:00      Communications               2
3  2024-08-01 11:48:00      Communications               3
4  2024-08-01 11:50:00      Communications               0

                                      topic_keywords  hour
0  Topic 1: voucher, sir, apolog, miss, refund, g...     6
1  Topic 1: voucher, sir, apolog, miss, refund, g...     6
2  Topic 1: voucher, sir, apolog, miss, refund, g...     9
3  Topic 1: voucher, sir, apolog, miss, refund, g...    11
4  Topic 1: voucher, sir, apolog, miss, refund, g...    11
Filtered DataFrame for reason_16:
      call_id  call_start_datetime agent_assigned_datetime  \
0  9310693795  2024-08-01 05:52:00     2024-08-01 06:02:00
1  4458776244  2024-08-01 06:00:00     2024-08-01 06:09:00
2  5842119015  2024-08-01 07:38:00     2024-08-01 07:47:00
3   471919827  2024-08-01 08:21:00     2024-08-01 08:31:00
4  6626993147  2024-08-01 09:02:00     2024-08-01 09:11:00

     call_end_datetime primary_call_reason  dominant_topic  \
0  2024-08-01 06:06:00             Seating               3
1  2024-08-01 06:24:00             Seating               3
2  2024-08-01 07:51:00             Seating               1
3  2024-08-01 08:37:00             Seating               0
4  2024-08-01 09:16:00             Seating               3

                                      topic_keywords  hour
0  Topic 1: 150, monday, great, friday, differ, w...     5
1  Topic 1: 150, monday, great, friday, differ, w...     6
2  Topic 1: 150, monday, great, friday, differ, w...     7
3  Topic 1: 150, monday, great, friday, differ, w...     8
4  Topic 1: 150, monday, great, friday, differ, w...     9
Filtered DataFrame for reason_17:
      call_id  call_start_datetime agent_assigned_datetime  \
0  3817230689  2024-08-01 05:03:00     2024-08-01 05:12:00
1  4886165173  2024-08-01 05:26:00     2024-08-01 05:36:00
2  5401438897  2024-08-01 09:00:00     2024-08-01 09:09:00
3  6062040810  2024-08-01 09:13:00     2024-08-01 09:22:00
4   949356313  2024-08-01 09:20:00     2024-08-01 09:30:00

     call_end_datetime primary_call_reason  dominant_topic  \
0  2024-08-01 05:25:00         Post Flight               3
1  2024-08-01 06:20:00         Post Flight               1
2  2024-08-01 09:41:00         Post Flight               3
3  2024-08-01 09:35:00         Post Flight               3
4  2024-08-01 09:58:00         Post Flight               1

                                      topic_keywords  hour
0  Topic 1: voucher, weather, experi, provid, mis...     5
1  Topic 1: voucher, weather, experi, provid, mis...     5
2  Topic 1: voucher, weather, experi, provid, mis...     9
3  Topic 1: voucher, weather, experi, provid, mis...     9
4  Topic 1: voucher, weather, experi, provid, mis...     9
Filtered DataFrame for reason_18:
      call_id  call_start_datetime agent_assigned_datetime  \
0  2506680660  2024-08-18 17:58:00     2024-08-18 18:09:00
1  2057129972  2024-08-01 10:23:00     2024-08-01 10:34:00
2  8486001848  2024-08-01 11:29:00     2024-08-01 11:37:00
3  4085701055  2024-08-02 00:44:00     2024-08-02 00:54:00
4  3747930098  2024-08-02 12:29:00     2024-08-02 12:40:00

     call_end_datetime primary_call_reason  dominant_topic  \
0  2024-08-18 18:19:00    Voluntary Cancel               3
1  2024-08-01 10:40:00    Voluntary Cancel               0
2  2024-08-01 11:54:00    Voluntary Cancel               0
3  2024-08-02 00:58:00    Voluntary Cancel               0
4  2024-08-02 12:46:00    Voluntary Cancel               3

                                      topic_keywords  hour
0  Topic 1: voucher, sir, apolog, refund, miss, g...    17
1  Topic 1: voucher, sir, apolog, refund, miss, g...    10
2  Topic 1: voucher, sir, apolog, refund, miss, g...    11
3  Topic 1: voucher, sir, apolog, refund, miss, g...     0
4  Topic 1: voucher, sir, apolog, refund, miss, g...    12
Filtered DataFrame for reason_19:
      call_id  call_start_datetime agent_assigned_datetime  \
0  2868853212  2024-08-01 09:44:00     2024-08-01 09:51:00
1  9619729032  2024-08-02 16:40:00     2024-08-02 16:48:00
2  3683977688  2024-08-02 20:54:00     2024-08-02 21:04:00
3  3583811471  2024-08-02 21:13:00     2024-08-02 21:22:00
4    25369057  2024-08-03 00:15:00     2024-08-03 00:23:00

     call_end_datetime primary_call_reason  dominant_topic  \
0  2024-08-01 09:55:00          Disability               2
1  2024-08-02 16:50:00          Disability               3
2  2024-08-02 21:06:00          Disability               3
3  2024-08-02 21:24:00          Disability               3
4  2024-08-03 00:27:00          Disability               2

                                      topic_keywords  hour
0  Topic 1: refund, voucher, credit, provid, expe...     9
1  Topic 1: refund, voucher, credit, provid, expe...    16
2  Topic 1: refund, voucher, credit, provid, expe...    20
3  Topic 1: refund, voucher, credit, provid, expe...    21

In [272]:
grouped_reason_dict = {}

for key, df in filtered_reason_dict.items():
    if 'dominant_topic' in df.columns: 
        grouped_reason_dict[key] = df.groupby('dominant_topic').size()  # Replace `.sum()` with desired aggregation function
    
        # Optional: Print to check the groupby operation
        print(f"Grouped DataFrame for {key}:")
        print(grouped_reason_dict[key].head())

# Now grouped_reason_dict holds the grouped DataFrames

Grouped DataFrame for reason_1:
dominant_topic
0    16
1    17
2    41
3    30
dtype: int64
Grouped DataFrame for reason_2:
dominant_topic
0     126
1    1027
2     371
3     364
dtype: int64
Grouped DataFrame for reason_3:
dominant_topic
0     973
1     631
2    1397
3     331
dtype: int64
Grouped DataFrame for reason_4:
dominant_topic
0    154
1    119
2    359
3     99
dtype: int64
Grouped DataFrame for reason_5:
dominant_topic
0    346
1    191
2    856
3    511
dtype: int64
Grouped DataFrame for reason_6:
dominant_topic
0    142
1    176
2    116
3    384
dtype: int64
Grouped DataFrame for reason_7:
dominant_topic
0    162
1    214
2    279
3    297
dtype: int64
Grouped DataFrame for reason_8:
dominant_topic
0    1417
1     681
2     343
3     391
dtype: int64
Grouped DataFrame for reason_9:
dominant_topic
0    2564
1    1528
2    3265
3    3491
dtype: int64
Grouped DataFrame for reason_11:
dominant_topic
0     860
1     839
2    1285
3    2867
dtype: int64
Grouped DataFrame for reason_12:
dominant_topic
0    1577
1    2863
2    6505
3    2366
dtype: int64
Grouped DataFrame for reason_13:
dominant_topic
0    962
1    560
2    534
3    682
dtype: int64
Grouped DataFrame for reason_14:
dominant_topic
0    166
1    222
2    342
3    207
dtype: int64
Grouped DataFrame for reason_15:
dominant_topic
0    1261
1    1873
2     240
3     466
dtype: int64
Grouped DataFrame for reason_16:
dominant_topic
0    2890
1     591
2     646
3    2238
dtype: int64
Grouped DataFrame for reason_17:
dominant_topic
0     686
1    1073
2     274
3    2297
dtype: int64
Grouped DataFrame for reason_18:
dominant_topic
0    565
1    140
2    418
3    484
dtype: int64
Grouped DataFrame for reason_19:
dominant_topic
0     58
1     15
2     96
3    234
dtype: int64
Grouped DataFrame for reason_20:
dominant_topic
0    524
1    187
2    284
3    230
dtype: int64
Grouped DataFrame for reason_21:
dominant_topic
0    1262
1     559
2     427
3     389
dtype: int64

In [274]:
grouped_reason_dict['reason_3']

dominant_topic
0     973
1     631
2    1397
3     331
dtype: int64

In [275]:
for reason, df in filtered_reason_dict.items():
    if all(col in df.columns for col in ['call_start_datetime', 'agent_assigned_datetime', 'call_end_datetime']):
        df['handle_time'] = (pd.to_datetime(df['call_end_datetime']) - pd.to_datetime(df['agent_assigned_datetime'])).dt.total_seconds() / 60
        df['wait_time'] = (pd.to_datetime(df['agent_assigned_datetime']) - pd.to_datetime(df['call_start_datetime'])).dt.total_seconds() / 60

In [276]:
handle_time_by_topic = {}
for reason,df in filtered_reason_dict.items():
    if all(col in df.columns for col in ['handle_time', 'dominant_topic', 'primary_call_reason']):
        grouped_df = pd.DataFrame(df.groupby(['dominant_topic'])['handle_time'].mean())
        
        handle_time_by_topic[reason] = {
                'grouped_handle_time': grouped_df,
                'primary_call_reason': df['primary_call_reason'].unique()  # Store unique values or all rows if needed
            }

In [277]:
grouped_reason_dict = {}

for key, df in filtered_reason_dict.items():
    if 'dominant_topic' in df.columns: 
        # Group by 'dominant_topic' and count occurrences
        grouped_df = df.groupby('dominant_topic').size().reset_index(name='count')
        
        # Add the primary call reason
        primary_reason = df['primary_call_reason'].unique()[0]  # Get unique primary call reason
        grouped_df['primary_call_reason'] = primary_reason
        
        # Store the DataFrame in the dictionary
        grouped_reason_dict[key] = grouped_df

        # Optional: Print to check the groupby operation
        print(f"Grouped DataFrame for {key}:")
        print(grouped_reason_dict[key].head())

Grouped DataFrame for reason_1:
   dominant_topic  count  primary_call_reason
0               0     16  Unaccompanied Minor
1               1     17  Unaccompanied Minor
2               2     41  Unaccompanied Minor
3               3     30  Unaccompanied Minor
Grouped DataFrame for reason_2:
   dominant_topic  count primary_call_reason
0               0    126            Checkout
1               1   1027            Checkout
2               2    371            Checkout
3               3    364            Checkout
Grouped DataFrame for reason_3:
   dominant_topic  count    primary_call_reason
0               0    973  Products and Services
1               1    631  Products and Services
2               2   1397  Products and Services
3               3    331  Products and Services
Grouped DataFrame for reason_4:
   dominant_topic  count primary_call_reason
0               0    154     Schedule Change
1               1    119     Schedule Change
2               2    359     Schedule Change
3               3     99     Schedule Change
Grouped DataFrame for reason_5:
   dominant_topic  count primary_call_reason
0               0    346            Check In
1               1    191            Check In
2               2    856            Check In
3               3    511            Check In
Grouped DataFrame for reason_6:
   dominant_topic  count primary_call_reason
0               0    142        Other Topics
1               1    176        Other Topics
2               2    116        Other Topics
3               3    384        Other Topics
Grouped DataFrame for reason_7:
   dominant_topic  count primary_call_reason
0               0    162                 ETC
1               1    214                 ETC
2               2    279                 ETC
3               3    297                 ETC
Grouped DataFrame for reason_8:
   dominant_topic  count primary_call_reason
0               0   1417             Baggage
1               1    681             Baggage
2               2    343             Baggage
3               3    391             Baggage
Grouped DataFrame for reason_9:
   dominant_topic  count primary_call_reason
0               0   2564    Voluntary Change
1               1   1528    Voluntary Change
2               2   3265    Voluntary Change
3               3   3491    Voluntary Change
Grouped DataFrame for reason_11:
   dominant_topic  count primary_call_reason
0               0    860        Mileage Plus
1               1    839        Mileage Plus
2               2   1285        Mileage Plus
3               3   2867        Mileage Plus
Grouped DataFrame for reason_12:
   dominant_topic  count primary_call_reason
0               0   1577              IRROPS
1               1   2863              IRROPS
2               2   6505              IRROPS
3               3   2366              IRROPS
Grouped DataFrame for reason_13:
   dominant_topic  count primary_call_reason
0               0    962             Upgrade
1               1    560             Upgrade
2               2    534             Upgrade
3               3    682             Upgrade
Grouped DataFrame for reason_14:
   dominant_topic  count primary_call_reason
0               0    166    Traveler Updates
1               1    222    Traveler Updates
2               2    342    Traveler Updates
3               3    207    Traveler Updates
Grouped DataFrame for reason_15:
   dominant_topic  count primary_call_reason
0               0   1261      Communications
1               1   1873      Communications
2               2    240      Communications
3               3    466      Communications
Grouped DataFrame for reason_16:
   dominant_topic  count primary_call_reason
0               0   2890             Seating
1               1    591             Seating
2               2    646             Seating
3               3   2238             Seating
Grouped DataFrame for reason_17:
   dominant_topic  count primary_call_reason
0               0    686         Post Flight
1               1   1073         Post Flight
2               2    274         Post Flight
3               3   2297         Post Flight
Grouped DataFrame for reason_18:
   dominant_topic  count primary_call_reason
0               0    565    Voluntary Cancel
1               1    140    Voluntary Cancel
2               2    418    Voluntary Cancel
3               3    484    Voluntary Cancel
Grouped DataFrame for reason_19:
   dominant_topic  count primary_call_reason
0               0     58          Disability
1               1     15          Disability
2               2     96          Disability
3               3    234          Disability
Grouped DataFrame for reason_20:
   dominant_topic  count primary_call_reason
0               0    524     Digital Support
1               1    187     Digital Support
2               2    284     Digital Support
3               3    230     Digital Support
Grouped DataFrame for reason_21:
   dominant_topic  count primary_call_reason
0               0   1262             Booking
1               1    559             Booking
2               2    427             Booking
3               3    389             Booking

In [278]:
grouped_reason_dict['reason_1']

   dominant_topic  count  primary_call_reason
0               0     16  Unaccompanied Minor
1               1     17  Unaccompanied Minor
2               2     41  Unaccompanied Minor
3               3     30  Unaccompanied Minor

In [279]:
combined_df = pd.concat(grouped_reason_dict.values(), ignore_index=True)
combined_df

    dominant_topic  count    primary_call_reason
0                0     16    Unaccompanied Minor
1                1     17    Unaccompanied Minor
2                2     41    Unaccompanied Minor
3                3     30    Unaccompanied Minor
4                0    126               Checkout
5                1   1027               Checkout
6                2    371               Checkout
7                3    364               Checkout
8                0    973  Products and Services
9                1    631  Products and Services
10               2   1397  Products and Services
11               3    331  Products and Services
12               0    154        Schedule Change
13               1    119        Schedule Change
14               2    359        Schedule Change
15               3     99        Schedule Change
16               0    346               Check In
17               1    191               Check In
18               2    856               Check In
19               3    511               Check In
20               0    142           Other Topics
21               1    176           Other Topics
22               2    116           Other Topics
23               3    384           Other Topics
24               0    162                    ETC
25               1    214                    ETC
26               2    279                    ETC
27               3    297                    ETC
28               0   1417                Baggage
29               1    681                Baggage
30               2    343                Baggage
31               3    391                Baggage
32               0   2564       Voluntary Change
33               1   1528       Voluntary Change
34               2   3265       Voluntary Change
35               3   3491       Voluntary Change
36               0    860           Mileage Plus
37               1    839           Mileage Plus
38               2   1285           Mileage Plus
39               3   2867           Mileage Plus
40               0   1577                 IRROPS
41               1   2863                 IRROPS
42               2   6505                 IRROPS
43               3   2366                 IRROPS
44               0    962                Upgrade
45               1    560                Upgrade
46               2    534                Upgrade
47               3    682                Upgrade
48               0    166       Traveler Updates
49               1    222       Traveler Updates
50               2    342       Traveler Updates
51               3    207       Traveler Updates
52               0   1261         Communications
53               1   1873         Communications
54               2    240         Communications
55               3    466         Communications
56               0   2890                Seating
57               1    591                Seating
58               2    646                Seating
59               3   2238                Seating
60               0    686            Post Flight
61               1   1073            Post Flight
62               2    274            Post Flight
63               3   2297            Post Flight
64               0    565       Voluntary Cancel
65               1    140       Voluntary Cancel
66               2    418       Voluntary Cancel
67               3    484       Voluntary Cancel
68               0     58             Disability
69               1     15             Disability
70               2     96             Disability
71               3    234             Disability
72               0    524        Digital Support
73               1    187        Digital Support
74               2    284        Digital Support
75               3    230        Digital Support
76               0   1262                Booking
77               1    559                Booking
78               2    427                Booking
79               3    389                Booking

In [282]:
import pandas as pd

# Initialize an empty list to hold the rows for the final DataFrame
rows = []

# Iterate over the handle_time_by_topic dictionary
for reason, data in handle_time_by_topic.items():
    # Extract the grouped handle time DataFrame
    grouped_handle_time = data['grouped_handle_time']
    # Extract the unique primary call reason for the current reason
    primary_call_reason = data['primary_call_reason'][0]  # Assuming there's at least one unique value

    # Iterate over the grouped handle time DataFrame to extract handle time and dominant topics
    for dominant_topic, row in grouped_handle_time.iterrows():
        # Append a new row to the rows list
        rows.append({
            'primary_call_reason': primary_call_reason,
            'handle_time': row['handle_time'],
            'dominant_topic': dominant_topic
        })

# Create a DataFrame from the list of rows
final_handle_time_df = pd.DataFrame(rows)

# Display the resulting DataFrame
print(final_handle_time_df)

      primary_call_reason  handle_time  dominant_topic
0     Unaccompanied Minor     6.500000               0
1     Unaccompanied Minor     9.882353               1
2     Unaccompanied Minor     9.609756               2
3     Unaccompanied Minor     7.800000               3
4                Checkout    15.952381               0
5                Checkout    17.352483               1
6                Checkout    17.148248               2
7                Checkout    15.945055               3
8   Products and Services    13.250771               0
9   Products and Services    11.183835               1
10  Products and Services    12.584109               2
11  Products and Services    11.870091               3
12        Schedule Change     8.519481               0
13        Schedule Change     9.218487               1
14        Schedule Change     7.259053               2
15        Schedule Change     9.646465               3
16               Check In     9.367052               0
17               Check In     9.554974               1
18               Check In     9.920561               2
19               Check In     9.121331               3
20           Other Topics     5.478873               0
21           Other Topics     5.147727               1
22           Other Topics     5.922414               2
23           Other Topics     6.255208               3
24                    ETC    15.061728               0
25                    ETC    16.808411               1
26                    ETC    15.792115               2
27                    ETC    16.279461               3
28                Baggage     5.498236               0
29                Baggage     5.486050               1
30                Baggage     5.002915               2
31                Baggage     6.406650               3
32       Voluntary Change    10.822153               0
33       Voluntary Change    10.569372               1
34       Voluntary Change    10.953139               2
35       Voluntary Change    10.283300               3
36           Mileage Plus    17.596512               0
37           Mileage Plus    15.892729               1
38           Mileage Plus    16.075486               2
39           Mileage Plus    16.728636               3
40                 IRROPS    12.809765               0
41                 IRROPS    12.599721               1
42                 IRROPS    13.215527               2
43                 IRROPS    13.498309               3
44                Upgrade    10.930353               0
45                Upgrade    11.267857               1
46                Upgrade     9.998127               2
47                Upgrade     9.812317               3
48       Traveler Updates     6.963855               0
49       Traveler Updates     5.549550               1
50       Traveler Updates     6.622807               2
51       Traveler Updates     7.188406               3
52         Communications    13.421887               0
53         Communications    14.119060               1
54         Communications    14.320833               2
55         Communications    13.096567               3
56                Seating     7.783045               0
57                Seating     7.416244               1
58                Seating     8.088235               2
59                Seating     8.171582               3
60            Post Flight    17.132653               0
61            Post Flight    14.793103               1
62            Post Flight    15.379562               2
63            Post Flight    15.447976               3
64       Voluntary Cancel    13.307965               0
65       Voluntary Cancel     8.828571               1
66       Voluntary Cancel    10.765550               2
67       Voluntary Cancel    12.559917               3
68             Disability     5.655172               0
69             Disability     4.333333               1
70             Disability     4.385417               2
71             Disability     4.905983               3
72        Digital Support     6.250000               0
73        Digital Support     5.871658               1
74        Digital Support     6.274648               2
75        Digital Support     6.286957               3
76                Booking     7.131537               0
77                Booking     6.914132               1
78                Booking     7.651054               2
79                Booking     6.856041               3

In [283]:
final_handle_time_df

      primary_call_reason  handle_time  dominant_topic
0     Unaccompanied Minor     6.500000               0
1     Unaccompanied Minor     9.882353               1
2     Unaccompanied Minor     9.609756               2
3     Unaccompanied Minor     7.800000               3
4                Checkout    15.952381               0
5                Checkout    17.352483               1
6                Checkout    17.148248               2
7                Checkout    15.945055               3
8   Products and Services    13.250771               0
9   Products and Services    11.183835               1
10  Products and Services    12.584109               2
11  Products and Services    11.870091               3
12        Schedule Change     8.519481               0
13        Schedule Change     9.218487               1
14        Schedule Change     7.259053               2
15        Schedule Change     9.646465               3
16               Check In     9.367052               0
17               Check In     9.554974               1
18               Check In     9.920561               2
19               Check In     9.121331               3
20           Other Topics     5.478873               0
21           Other Topics     5.147727               1
22           Other Topics     5.922414               2
23           Other Topics     6.255208               3
24                    ETC    15.061728               0
25                    ETC    16.808411               1
26                    ETC    15.792115               2
27                    ETC    16.279461               3
28                Baggage     5.498236               0
29                Baggage     5.486050               1
30                Baggage     5.002915               2
31                Baggage     6.406650               3
32       Voluntary Change    10.822153               0
33       Voluntary Change    10.569372               1
34       Voluntary Change    10.953139               2
35       Voluntary Change    10.283300               3
36           Mileage Plus    17.596512               0
37           Mileage Plus    15.892729               1
38           Mileage Plus    16.075486               2
39           Mileage Plus    16.728636               3
40                 IRROPS    12.809765               0
41                 IRROPS    12.599721               1
42                 IRROPS    13.215527               2
43                 IRROPS    13.498309               3
44                Upgrade    10.930353               0
45                Upgrade    11.267857               1
46                Upgrade     9.998127               2
47                Upgrade     9.812317               3
48       Traveler Updates     6.963855               0
49       Traveler Updates     5.549550               1
50       Traveler Updates     6.622807               2
51       Traveler Updates     7.188406               3
52         Communications    13.421887               0
53         Communications    14.119060               1
54         Communications    14.320833               2
55         Communications    13.096567               3
56                Seating     7.783045               0
57                Seating     7.416244               1
58                Seating     8.088235               2
59                Seating     8.171582               3
60            Post Flight    17.132653               0
61            Post Flight    14.793103               1
62            Post Flight    15.379562               2
63            Post Flight    15.447976               3
64       Voluntary Cancel    13.307965               0
65       Voluntary Cancel     8.828571               1
66       Voluntary Cancel    10.765550               2
67       Voluntary Cancel    12.559917               3
68             Disability     5.655172               0
69             Disability     4.333333               1
70             Disability     4.385417               2
71             Disability     4.905983               3
72        Digital Support     6.250000               0
73        Digital Support     5.871658               1
74        Digital Support     6.274648               2
75        Digital Support     6.286957               3
76                Booking     7.131537               0
77                Booking     6.914132               1
78                Booking     7.651054               2
79                Booking     6.856041               3

In [285]:
final_df = final_handle_time_df.merge(combined_df,on=['primary_call_reason','dominant_topic'])

In [286]:
final_df

      primary_call_reason  handle_time  dominant_topic  count
0     Unaccompanied Minor     6.500000               0     16
1     Unaccompanied Minor     9.882353               1     17
2     Unaccompanied Minor     9.609756               2     41
3     Unaccompanied Minor     7.800000               3     30
4                Checkout    15.952381               0    126
5                Checkout    17.352483               1   1027
6                Checkout    17.148248               2    371
7                Checkout    15.945055               3    364
8   Products and Services    13.250771               0    973
9   Products and Services    11.183835               1    631
10  Products and Services    12.584109               2   1397
11  Products and Services    11.870091               3    331
12        Schedule Change     8.519481               0    154
13        Schedule Change     9.218487               1    119
14        Schedule Change     7.259053               2    359
15        Schedule Change     9.646465               3     99
16               Check In     9.367052               0    346
17               Check In     9.554974               1    191
18               Check In     9.920561               2    856
19               Check In     9.121331               3    511
20           Other Topics     5.478873               0    142
21           Other Topics     5.147727               1    176
22           Other Topics     5.922414               2    116
23           Other Topics     6.255208               3    384
24                    ETC    15.061728               0    162
25                    ETC    16.808411               1    214
26                    ETC    15.792115               2    279
27                    ETC    16.279461               3    297
28                Baggage     5.498236               0   1417
29                Baggage     5.486050               1    681
30                Baggage     5.002915               2    343
31                Baggage     6.406650               3    391
32       Voluntary Change    10.822153               0   2564
33       Voluntary Change    10.569372               1   1528
34       Voluntary Change    10.953139               2   3265
35       Voluntary Change    10.283300               3   3491
36           Mileage Plus    17.596512               0    860
37           Mileage Plus    15.892729               1    839
38           Mileage Plus    16.075486               2   1285
39           Mileage Plus    16.728636               3   2867
40                 IRROPS    12.809765               0   1577
41                 IRROPS    12.599721               1   2863
42                 IRROPS    13.215527               2   6505
43                 IRROPS    13.498309               3   2366
44                Upgrade    10.930353               0    962
45                Upgrade    11.267857               1    560
46                Upgrade     9.998127               2    534
47                Upgrade     9.812317               3    682
48       Traveler Updates     6.963855               0    166
49       Traveler Updates     5.549550               1    222
50       Traveler Updates     6.622807               2    342
51       Traveler Updates     7.188406               3    207
52         Communications    13.421887               0   1261
53         Communications    14.119060               1   1873
54         Communications    14.320833               2    240
55         Communications    13.096567               3    466
56                Seating     7.783045               0   2890
57                Seating     7.416244               1    591
58                Seating     8.088235               2    646
59                Seating     8.171582               3   2238
60            Post Flight    17.132653               0    686
61            Post Flight    14.793103               1   1073
62            Post Flight    15.379562               2    274
63            Post Flight    15.447976               3   2297
64       Voluntary Cancel    13.307965               0    565
65       Voluntary Cancel     8.828571               1    140
66       Voluntary Cancel    10.765550               2    418
67       Voluntary Cancel    12.559917               3    484
68             Disability     5.655172               0     58
69             Disability     4.333333               1     15
70             Disability     4.385417               2     96
71             Disability     4.905983               3    234
72        Digital Support     6.250000               0    524
73        Digital Support     5.871658               1    187
74        Digital Support     6.274648               2    284
75        Digital Support     6.286957               3    230
76                Booking     7.131537               0   1262
77                Booking     6.914132               1    559
78                Booking     7.651054               2    427
79                Booking     6.856041               3    389

In [288]:
keywords = pd.read_csv('keywords.csv')

In [289]:
keywords.tail()

,Unnamed: 0,Call Reason,Topic,Keywords
75,75,Checkout,3,"tomorrow, connect, ugh, denver, guess, york, u..."
76,76,Unaccompanied Minor,0,"return, monday, saturday, email, john, london,..."
77,77,Unaccompanied Minor,1,"sam, 150, great, paus, departur, glad, standbi..."
78,78,Unaccompanied Minor,2,"voucher, miss, apolog, sir, refund, guess, pro..."
79,79,Unaccompanied Minor,3,"san, francisco, tuesday, great, question, pay,..."

In [298]:
final_df= final_df.merge(keywords,left_on=['primary_call_reason','dominant_topic'],right_on=['Call Reason','Topic'])
final_df

,primary_call_reason,handle_time,dominant_topic,count,Unnamed: 0,Call Reason,Topic,Keywords
0,Unaccompanied Minor,6.500000,0,16,76,Unaccompanied Minor,0,"return, monday, saturday, email, john, london,..."
1,Unaccompanied Minor,9.882353,1,17,77,Unaccompanied Minor,1,"sam, 150, great, paus, departur, glad, standbi..."
2,Unaccompanied Minor,9.609756,2,41,78,Unaccompanied Minor,2,"voucher, miss, apolog, sir, refund, guess, pro..."
3,Unaccompanied Minor,7.800000,3,30,79,Unaccompanied Minor,3,"san, francisco, tuesday, great, question, pay,..."
4,Checkout,15.952381,0,126,72,Checkout,0,"credit, refund, offer, ticket, futur, abl, min..."
5,Checkout,17.352483,1,1027,73,Checkout,1,"great, 150, monday, return, thursday, tuesday,..."
6,Checkout,17.148248,2,371,74,Checkout,2,"weather, voucher, miss, experi, provid, bag, c..."
7,Checkout,15.945055,3,364,75,Checkout,3,"tomorrow, connect, ugh, denver, guess, york, u..."
8,Products and Services,13.250771,0,973,24,Products and Services,0,"sir, voucher, refund, apolog, guess, miss, pro..."
9,Products and Services,11.183835,1,631,25,Products and Services,1,"tomorrow, connect, denver, weather, safe, arri..."
10,Products and Services,12.584109,2,1397,26,Products and Services,2,"monday, return, great, 150, thursday, tuesday,..."
11,Products and Services,11.870091,3,331,27,Products and Services,3,"upgrad, bag, credit, economi, think, thing, ti..."
12,Schedule Change,8.519481,0,154,68,Schedule Change,0,"tomorrow, connect, sir, ugh, guess, york, miss..."
13,Schedule Change,9.218487,1,119,69,Schedule Change,1,"refund, voucher, experi, provid, compens, miss..."
14,Schedule Change,7.259053,2,359,70,Schedule Change,2,"150, monday, friday, great, thursday, tuesday,..."
15,Schedule Change,9.646465,3,99,71,Schedule Change,3,"weather, upgrad, question, bag, safe, mind, do..."
16,Check In,9.367052,0,346,64,Check In,0,"san, francisco, safe, question, feel, thing, g..."
17,Check In,9.554974,1,191,65,Check In,1,"experi, bag, refund, voucher, provid, offer, a..."
18,Check In,9.920561,2,856,66,Check In,2,"150, return, friday, monday, differ, great, pa..."
19,Check In,9.121331,3,511,67,Check In,3,"miss, tomorrow, sir, connect, apolog, voucher,..."
20,Other Topics,5.478873,0,142,60,Other Topics,0,"weather, question, departur, safe, bag, feel, ..."
21,Other Topics,5.147727,1,176,61,Other Topics,1,"tomorrow, connect, miss, sir, ugh, apolog, gue..."
22,Other Topics,5.922414,2,116,62,Other Topics,2,"refund, experi, voucher, sorri, compens, apolo..."
23,Other Topics,6.255208,3,384,63,Other Topics,3,"return, great, friday, monday, 150, differ, hm..."
24,ETC,15.061728,0,162,56,ETC,0,"tomorrow, connect, denver, miss, apolog, sir, ..."
25,ETC,16.808411,1,214,57,ETC,1,"refund, voucher, sir, provid, experi, apolog, ..."
26,ETC,15.792115,2,279,58,ETC,2,"san, francisco, great, tuesday, question, thur..."
27,ETC,16.279461,3,297,59,ETC,3,"friday, return, 150, monday, differ, waiv, pay..."
28,Baggage,5.498236,0,1417,52,Baggage,0,"150, friday, return, great, monday, tuesday, d..."
29,Baggage,5.486050,1,681,53,Baggage,1,"tomorrow, connect, sir, ugh, guess, apolog, in..."
30,Baggage,5.002915,2,343,54,Baggage,2,"question, weather, feel, london, safe, doubl, ..."
31,Baggage,6.406650,3,391,55,Baggage,3,"voucher, refund, experi, miss, provid, offer, ..."
32,Voluntary Change,10.822153,0,2564,32,Voluntary Change,0,"150, waiv, monday, differ, pay, credit, return..."
33,Voluntary Change,10.569372,1,1528,33,Voluntary Change,1,"upgrad, connect, denver, tomorrow, ugh, tri, a..."
34,Voluntary Change,10.953139,2,3265,34,Voluntary Change,2,"voucher, sir, apolog, miss, refund, provid, gu..."
35,Voluntary Change,10.283300,3,3491,35,Voluntary Change,3,"great, friday, depart, enjoy, email, san, retu..."
36,Mileage Plus,17.596512,0,860,28,Mileage Plus,0,"refund, voucher, experi, miss, provid, offer, ..."
37,Mileage Plus,15.892729,1,839,29,Mileage Plus,1,"question, weather, london, safe, departur, fee..."
38,Mileage Plus,16.075486,2,1285,30,Mileage Plus,2,"tomorrow, connect, sir, ugh, guess, miss, apol..."
39,Mileage Plus,16.728636,3,2867,31,Mileage Plus,3,"return, 150, monday, great, friday, thursday, ..."
40,IRROPS,12.809765,0,1577,20,IRROPS,0,"weather, london, feel, question, safe, upgrad,..."
41,IRROPS,12.599721,1,2863,21,IRROPS,1,"tomorrow, connect, sir, ugh, guess, apolog, in..."
42,IRROPS,13.215527,2,6505,22,IRROPS,2,"monday, 150, friday, great, tuesday, differ, t..."
43,IRROPS,13.498309,3,2366,23,IRROPS,3,"refund, voucher, experi, miss, compens, provid..."
44,Upgrade,10.930353,0,962,16,Upgrade,0,"150, monday, return, waiv, differ, tuesday, pa..."
45,Upgrade,11.267857,1,560,17,Upgrade,1,"voucher, refund, experi, provid, compens, miss..."
46,Upgrade,9.998127,2,534,18,Upgrade,2,"tomorrow, connect, ugh, sir, guess, denver, ap..."
47,Upgrade,9.812317,3,682,19,Upgrade,3,"great, question, safe, departur, think, email,..."
48,Traveler Updates,6.963855,0,166,12,Traveler Updates,0,"monday, tuesday, 150, waiv, sam, pay, 75, john..."
49,Traveler Updates,5.549550,1,222,13,Traveler Updates,1,"san, francisco, return, great, think, safe, qu..."
50,Traveler Updates,6.622807,2,342,14,Traveler Updates,2,"sir, apolog, voucher, miss, guess, refund, con..."
51,Traveler Updates,7.188406,3,207,15,Traveler Updates,3,"friday, differ, saturday, thursday, great, pay..."
52,Communications,13.421887,0,1261,8,Communications,0,"voucher, sir, apolog, miss, refund, guess, tom..."
53,Communications,14.119060,1,1873,9,Communications,1,"150, monday, return, great, friday, differ, wa..."
54,Communications,14.320833,2,240,10,Communications,2,"upgrad, economi, tri, standbi, class, open, ba..."
55,Communications,13.096567,3,466,11,Communications,3,"weather, connect, denver, safe, london, arriv,..."
56,Seating,7.783045,0,2890,4,Seating,0,"150, monday, great, friday, differ, waiv, tues..."
57,Seating,7.416244,1,591,5,Seating,1,"upgrad, bag, doubl, question, economi, everyth..."
58,Seating,8.088235,2,646,6,Seating,2,"london, weather, safe, feel, return, thing, de..."
59,Seating,8.171582,3,2238,7,Seating,3,"voucher, sir, apolog, miss, tomorrow, guess, r..."
60,Post Flight,17.132653,0,686,0,Post Flight,0,"voucher, weather, experi, provid, miss, bag, r..."
61,Post Flight,14.793103,1,1073,1,Post Flight,1,"tomorrow, sir, apolog, ugh, connect, guess, in..."
62,Post Flight,15.379562,2,274,2,Post Flight,2,"credit, refund, ticket, abl, use, offer, 200, ..."
63,Post Flight,15.447976,3,2297,3,Post Flight,3,"great, monday, return, tuesday, thursday, frid..."
64,Voluntary Cancel,13.307965,0,565,48,Voluntary Cancel,0,"voucher, sir, apolog, refund, miss, guess, sor..."
65,Voluntary Cancel,8.828571,1,140,49,Voluntary Cancel,1,"connect, weather, san, francisco, safe, arriv,..."
66,Voluntary Cancel,10.765550,2,418,50,Voluntary Cancel,2,"great, upgrad, saturday, return, convers, lond..."
67,Voluntary Cancel,12.559917,3,484,51,Voluntary Cancel,3,"150, monday, waiv, differ, pay, san, francisco..."
68,Disability,5.655172,0,58,44,Disability,0,"refund, voucher, credit, provid, experi, futur..."
69,Disability,4.333333,1,15,45,Disability,1,"upgrad, bag, class, apolog, economi, guess, si..."
70,Disability,4.385417,2,96,46,Disability,2,"connect, miss, tomorrow, denver, ugh, guess, s..."
71,Disability,4.905983,3,234,47,Disability,3,"great, thursday, return, friday, 150, tuesday,..."
72,Digital Support,6.250000,0,524,40,Digital Support,0,"150, monday, friday, return, differ, tuesday, ..."
73,Digital Support,5.871658,1,187,41,Digital Support,1,"refund, credit, voucher, provid, experi, offer..."
74,Digital Support,6.274648,2,284,42,Digital Support,2,"connect, tomorrow, miss, apolog, sir, guess, v..."
75,Digital Support,6.286957,3,230,43,Digital Support,3,"san, francisco, question, upgrad, safe, weathe..."
76,Booking,7.131537,0,1262,36,Booking,0,"monday, return, 150, friday, tuesday, great, d..."
77,Booking,6.914132,1,559,37,Booking,1,"tomorrow, connect, sir, ugh, guess, apolog, de..."
78,Booking,7.651054,2,427,38,Booking,2,"voucher, refund, experi, provid, miss, sir, co..."
79,Booking,6.856041,3,389,39,Booking,3,"question, weather, london, safe, depart, great..."

In [299]:
final_df.drop(columns={'Unnamed: 0','Topic','Call Reason'},inplace=True)

In [301]:
final_df.to_csv('final_analysis_part2.csv')